name = "PkEisensteinHu"
uuid = "ee70d5b0-4c26-4f62-a7c4-21cc121a7fe1"
authors = ["Henry Gebhardt <hsggebhardt@fastmail.com> and contributors"]
version = "0.3.0"

[compat]
julia = "1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
